# This is a basic workflow to help you get started with Actions
name: Build UI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - dev
      - feature/*
      - fix/*
      - perf/*
      - refactor/*
      - build/*
      - build/github-ci
  pull_request:
    branches:
      - dev
      - feature/*
      - fix/*
      - perf/*
      - refactor/*
      - build/*
      - build/github-ci

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install rpm -y
          npm i pnpm@^8.6.9 -g
          cd packages/ui
          pnpm i --force

      - name: Build
        run: |
          node ./scripts/github-ci-build.mjs